### Numpy Continuation
##### Random Method

In [3]:
import numpy as np


In [6]:
# Generate Single interger value
np.random.randint(100)


74

In [12]:
#generate float value range of 0 to 1
np.random.rand(3,5)

array([[0.27803404, 0.52076349, 0.31665597, 0.91235181, 0.35298962],
       [0.76490962, 0.2010224 , 0.15852862, 0.45157053, 0.37762636],
       [0.1080178 , 0.71824666, 0.19590423, 0.77490068, 0.02679551]])

In [13]:
np.random.randint(10,100,size=(10)) #ID

array([87, 33, 54, 36, 73, 95, 81, 20, 37, 17])

In [20]:
np.random.randint(10,100,size=(2,3)) #2D

array([[96, 40, 99],
       [89, 88, 45]])

In [24]:
np.random.randint(5,10,size=(2,3,4)) #3D

array([[[6, 9, 5, 7],
        [7, 9, 8, 8],
        [6, 7, 9, 7]],

       [[9, 7, 6, 8],
        [9, 5, 6, 8],
        [5, 8, 5, 6]]])

In [25]:
np.random.randint(2,10,size=(2,2,2,3,4)) #5D

array([[[[[6, 8, 6, 4],
          [7, 3, 7, 2],
          [2, 7, 5, 8]],

         [[5, 4, 3, 7],
          [7, 6, 6, 4],
          [4, 9, 9, 6]]],


        [[[9, 3, 9, 5],
          [3, 9, 5, 3],
          [7, 5, 9, 3]],

         [[2, 3, 5, 8],
          [4, 8, 8, 8],
          [6, 8, 8, 3]]]],



       [[[[2, 8, 2, 2],
          [2, 9, 6, 5],
          [3, 5, 6, 8]],

         [[2, 8, 6, 9],
          [7, 7, 4, 8],
          [4, 7, 7, 4]]],


        [[[6, 8, 4, 3],
          [6, 6, 8, 3],
          [7, 7, 7, 9]],

         [[5, 3, 5, 6],
          [2, 3, 2, 5],
          [8, 9, 6, 2]]]]])

In [31]:
np.random.choice([10,2,3,6,4,5]) #Choice of numbers

6

In [33]:
np.random.choice([10,2,3,6,4,5],size=(5,5)) 

array([[ 5,  4, 10,  2,  5],
       [ 2, 10,  2,  5,  5],
       [10,  6,  3,  3, 10],
       [ 4,  4, 10,  5,  2],
       [ 2, 10, 10, 10,  3]])

In [36]:
np.random.choice([10,2,3,6,4],p=[0.6,0,0.1,0.2,0.1])

10

In [37]:
np.random.choice([10,2,3,6,4],p=[0.6,0,0.1,0.2,0.1],size=(3,3))

array([[ 4,  6, 10],
       [ 4, 10,  6],
       [10, 10, 10]])

In [6]:
a=np.array([[2,3,6,5],[4,5,6,9]])
a

array([[2, 3, 6, 5],
       [4, 5, 6, 9]])

In [7]:
b=np.random.shuffle(a)
b

### Array Filtering

In [17]:
a=np.array([1,2,3,6,5])
b=np.array([True,False,True,False,True])
c=a[b]
a1=a[a<3]
a1

array([1, 2])

In [18]:
a

array([1, 2, 3, 6, 5])

In [20]:
np.dot(a,b)

9

In [21]:
a.T

array([1, 2, 3, 6, 5])

## Pandas

In [22]:
import pandas as pd

In [23]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'c:\users\lenovo_pc\appdata\local\programs\python\python36\python.exe -m pip install --upgrade pip' command.


In [25]:
len(dir(pd))

151

In [26]:
pd.__version__

'1.0.0'

### Series
* The Data is in the format of 1D
* The Output is in the format of row wise

In [27]:
# Creating the data in series
a=pd.Series([1,2,3,6,6])
a

0    1
1    2
2    3
3    6
4    6
dtype: int64

In [29]:
# creatting series by using numpy
import numpy as np
a=pd.Series(np.arange(1,5))
a

0    1
1    2
2    3
3    4
dtype: int32

In [30]:
# Creating the series using tuple
a=pd.Series((1,2,3,6,6))
a

0    1
1    2
2    3
3    6
4    6
dtype: int64

In [31]:
# Creating the series using dic
a=pd.Series({1:2,2:'one',3:"three"})
a

1        2
2      one
3    three
dtype: object

In [35]:
# Change index values
a=pd.Series([1,2,3,4],index=np.arange(6,10))
a

6    1
7    2
8    3
9    4
dtype: int64

In [40]:
a=[1,2,3,4,5,'k']
b=pd.Series(a,index=np.arange(1,len(a)+1))
b

1    1
2    2
3    3
4    4
5    5
6    k
dtype: object

In [41]:
b.dtype

dtype('O')

### DataFrames

In [49]:
b=[1,2,3,4]
c=pd.DataFrame(b,index=np.arange(1,len(b)+1))
c

0
1  1
2  2
3  3
4  4

In [50]:
# Craeting dataframe using multible vdata
c=pd.DataFrame([['a',10,11],['b',10,25],['c',40,25]])
c

0   1   2
0  a  10  11
1  b  10  25
2  c  40  25

In [52]:
# For Adding Columns Names
c=pd.DataFrame([['a',10,11],['b',10,25],['c',40,25]],columns=['Name','Year','values'])
c

Name  Year  values
0    a    10      11
1    b    10      25
2    c    40      25

In [53]:
# For Adding Columns Names
c=pd.DataFrame([['a',10,11],['b',10,25],['c',40,25]],columns=['Name','Year','values'],index=[10,11,12])
c

Name  Year  values
10    a    10      11
11    b    10      25
12    c    40      25

In [55]:
d={'names':['srinivas','lucky','viswanth'],
  'years':[1995,1997,2018],
  'batch':[1,2,3]}
a=pd.DataFrame(d,index=[1,2,3])
a

names  years  batch
1  srinivas   1995      1
2     lucky   1997      2
3  viswanth   2018      3

In [60]:
## Craeting dataframes using multiple dics
data=[{1:'one',2:'two',3:"three"},
     {1:'six',2:'seven',3:'nnine'}]
a=pd.DataFrame(data,index=['a','b'])
a

1      2      3
a  one    two  three
b  six  seven  nnine

In [62]:
## Converting Series to DataFrames
d={'one':pd.Series([1,2,3,4]),
  "two":pd.Series([4,5,6,7]),
  'Three':pd.Series([0,6])}
pd.DataFrame(d,dtype=complex)

one                 two               Three
0  1.000000+0.000000j  4.000000+0.000000j  0.000000+0.000000j
1  2.000000+0.000000j  5.000000+0.000000j  6.000000+0.000000j
2  3.000000+0.000000j  6.000000+0.000000j                 NaN
3  4.000000+0.000000j  7.000000+0.000000j                 NaN

#### Indexing and Slicing

#### Series indexing


In [66]:
s=pd.Series([99,88,77,44,55,66])
s

0    99
1    88
2    77
3    44
4    55
5    66
dtype: int64

In [69]:
s.index=['a','b','c',1,2,3]
s

a    99
b    88
c    77
1    44
2    55
3    66
dtype: int64

In [75]:
s[1:3]

b    88
c    77
dtype: int64

In [71]:
s['a']

99

In [72]:
s['a':'c'] #Explict indexinng

a    99
b    88
c    77
dtype: int64

In [74]:
s["c":]

c    77
1    44
2    55
3    66
dtype: int64

In [78]:
s[['a',1]]

a    99
1    44
dtype: int64

In [81]:
s[[-1]]

3    66
dtype: int64

In [82]:
d={'names':['srinivas','lucky','viswanth'],
  'years':[1995,1997,2018],
  'batch':[1,2,3]}
a=pd.DataFrame(d,index=[1,2,3])
a

names  years  batch
1  srinivas   1995      1
2     lucky   1997      2
3  viswanth   2018      3

In [83]:
a.values

array([['srinivas', 1995, 1],
       ['lucky', 1997, 2],
       ['viswanth', 2018, 3]], dtype=object)

In [84]:
a.index

Int64Index([1, 2, 3], dtype='int64')

In [85]:
a['names']

1    srinivas
2       lucky
3    viswanth
Name: names, dtype: object

In [88]:
a['names'][3]

'viswanth'

In [90]:
a[:-1]

names  years  batch
1  srinivas   1995      1
2     lucky   1997      2

In [92]:
a.head()

names  years  batch
1  srinivas   1995      1
2     lucky   1997      2
3  viswanth   2018      3

In [94]:
a.tail(1)

names  years  batch
3  viswanth   2018      3

In [95]:
a.columns

Index(['names', 'years', 'batch'], dtype='object')

### iloc and loc

In [100]:
a=pd.DataFrame([[1,2,3,4],[45,4,5,6]],columns=['a','b','c','d'])
a

a  b  c  d
0   1  2  3  4
1  45  4  5  6

In [106]:
a.loc[1]

a    45
b     4
c     5
d     6
Name: 1, dtype: int64

In [108]:
a.iloc[0]

a    1
b    2
c    3
d    4
Name: 0, dtype: int64

In [109]:
a.iloc[1]

a    45
b     4
c     5
d     6
Name: 1, dtype: int64

In [112]:
a.iloc[1][-1]

6

### Date Range using Series

In [115]:
s = pd.date_range(start='2020-11-27',end='2020-12-27')
len(s)
s

DatetimeIndex(['2020-11-27', '2020-11-28', '2020-11-29', '2020-11-30',
               '2020-12-01', '2020-12-02', '2020-12-03', '2020-12-04',
               '2020-12-05', '2020-12-06', '2020-12-07', '2020-12-08',
               '2020-12-09', '2020-12-10', '2020-12-11', '2020-12-12',
               '2020-12-13', '2020-12-14', '2020-12-15', '2020-12-16',
               '2020-12-17', '2020-12-18', '2020-12-19', '2020-12-20',
               '2020-12-21', '2020-12-22', '2020-12-23', '2020-12-24',
               '2020-12-25', '2020-12-26', '2020-12-27'],
              dtype='datetime64[ns]', freq='D')

In [116]:
help(pd.date_range)

Help on function date_range in module pandas.core.indexes.datetimes:

date_range(start=None, end=None, periods=None, freq=None, tz=None, normalize=False, name=None, closed=None, **kwargs) -> pandas.core.indexes.datetimes.DatetimeIndex
    Return a fixed frequency DatetimeIndex.
    
    Parameters
    ----------
    start : str or datetime-like, optional
        Left bound for generating dates.
    end : str or datetime-like, optional
        Right bound for generating dates.
    periods : int, optional
        Number of periods to generate.
    freq : str or DateOffset, default 'D'
        Frequency strings can have multiples, e.g. '5H'. See
        :ref:`here <timeseries.offset_aliases>` for a list of
        frequency aliases.
    tz : str or tzinfo, optional
        Time zone name for returning localized DatetimeIndex, for example
        'Asia/Hong_Kong'. By default, the resulting DatetimeIndex is
        timezone-naive.
    normalize : bool, default False
        Normalize start/

In [120]:
s = pd.date_range(start='2020-11-27',periods=5,freq='3M')
len(s)
s

DatetimeIndex(['2020-11-30', '2021-02-28', '2021-05-31', '2021-08-31',
               '2021-11-30'],
              dtype='datetime64[ns]', freq='3M')

In [ ]:
### Deleteing a particularcolumn from the fstaframe


### Combining and mergeing of DfS

In [130]:
a={'name':['srinivas','lucky','viswanth'],
  'year':[1995,1997,2018],
  'gender':['male','female','male']}
b=pd.DataFrame(a,index=[11,22,33])
b

name  year  gender
11  srinivas  1995    male
22     lucky  1997  female
33  viswanth  2018    male

In [131]:
pd.concat([b,b]) #Row Concat

name  year  gender
11  srinivas  1995    male
22     lucky  1997  female
33  viswanth  2018    male
11  srinivas  1995    male
22     lucky  1997  female
33  viswanth  2018    male

In [132]:
pd.concat([b,b],axis=1) #Column Concat

name  year  gender      name  year  gender
11  srinivas  1995    male  srinivas  1995    male
22     lucky  1997  female     lucky  1997  female
33  viswanth  2018    male  viswanth  2018    male

In [134]:
b.append(b) ## only row wise appending

name  year  gender
11  srinivas  1995    male
22     lucky  1997  female
33  viswanth  2018    male
11  srinivas  1995    male
22     lucky  1997  female
33  viswanth  2018    male

In [135]:
pd.merge(b,b)

name  year  gender
0  srinivas  1995    male
1     lucky  1997  female
2  viswanth  2018    male

In [145]:
a={'name':['srinivas','lucky','viswanth'],
  'y':[1995,1997,2018],
  'age':[12,3,6]}
a=pd.DataFrame(a)
a

name     y  age
0  srinivas  1995   12
1     lucky  1997    3
2  viswanth  2018    6

In [137]:
b

name  year  gender
11  srinivas  1995    male
22     lucky  1997  female
33  viswanth  2018    male

In [141]:
pd.concat([a,b])

n       y   age      name    year  gender
0   srinivas  1995.0  12.0       NaN     NaN     NaN
1      lucky  1997.0   3.0       NaN     NaN     NaN
2   viswanth  2018.0   6.0       NaN     NaN     NaN
11       NaN     NaN   NaN  srinivas  1995.0    male
22       NaN     NaN   NaN     lucky  1997.0  female
33       NaN     NaN   NaN  viswanth  2018.0    male

In [146]:
pd.merge(a,b) ## Common columns are merged

name     y  age  year  gender
0  srinivas  1995   12  1995    male
1     lucky  1997    3  1997  female
2  viswanth  2018    6  2018    male

In [147]:
pd.merge(a,b,how='left')

name     y  age  year  gender
0  srinivas  1995   12  1995    male
1     lucky  1997    3  1997  female
2  viswanth  2018    6  2018    male

In [148]:
pd.merge(a,b,how='right')

name     y  age  year  gender
0  srinivas  1995   12  1995    male
1     lucky  1997    3  1997  female
2  viswanth  2018    6  2018    male

In [149]:
pd.merge(b,a,how='outer') #Union of both DFs

name  year  gender     y  age
0  srinivas  1995    male  1995   12
1     lucky  1997  female  1997    3
2  viswanth  2018    male  2018    6

In [150]:
pd.merge(b,a,how='inner')

name  year  gender     y  age
0  srinivas  1995    male  1995   12
1     lucky  1997  female  1997    3
2  viswanth  2018    male  2018    6

In [152]:
help(pd.merge)

Help on function merge in module pandas.core.reshape.merge:

merge(left, right, how:str='inner', on=None, left_on=None, right_on=None, left_index:bool=False, right_index:bool=False, sort:bool=False, suffixes=('_x', '_y'), copy:bool=True, indicator:bool=False, validate=None) -> 'DataFrame'
    Merge DataFrame or named Series objects with a database-style join.
    
    The join is done on columns or indexes. If joining columns on
    columns, the DataFrame indexes *will be ignored*. Otherwise if joining indexes
    on indexes or indexes on a column or columns, the index will be passed on.
    
    Parameters
    ----------
    left : DataFrame
    right : DataFrame or named Series
        Object to merge with.
    how : {'left', 'right', 'outer', 'inner'}, default 'inner'
        Type of merge to be performed.
    
        * left: use only keys from left frame, similar to a SQL left outer join;
          preserve key order.
        * right: use only keys from right frame, similar to a S

### File Reading

In [158]:
a=pd.read_csv('birds.csv')
b=pd.DataFrame(a,index=np.arange(1,len(a)+1))
b.head()

id   huml  humw  ulnal  ulnaw   feml  femw   tibl  tibw   tarl  tarw type
1  1.0  88.91  6.63  80.53   5.59  47.04  4.30  80.22  4.51  41.50  4.01   SW
2  2.0  79.97  6.37  69.26   5.28  43.07  3.90  75.35  4.04  38.31  3.34   SW
3  3.0  77.65  5.70  65.76   4.77  40.04  3.52  69.17  3.40  35.78  3.41   SW
4  4.0  62.80  4.84  52.09   3.73  33.95  2.72  56.27  2.96  31.88  3.13   SW
5  5.0  61.92  4.78  50.46   3.47  49.52  4.41  56.95  2.73  29.07  2.83   SW

In [156]:
a.tail(3)

id   huml  humw  ulnal  ulnaw   feml  femw   tibl  tibw   tarl  tarw  \
417  417  18.79  1.63  19.83   1.53  20.96  1.43  34.45  1.41  22.86  1.21   
418  418  20.38  1.78  22.53   1.50  21.35  1.48  36.09  1.53  25.98  1.24   
419  419  17.89  1.44  19.26   1.10  17.62  1.34  29.81  1.24  21.69  1.05   

    type  
417   SO  
418   SO  
419   SO

In [162]:
b['ulnal'][5]

50.46