data is raw input of mat
after some purification and filltering 

DA is the process of collectiong and organizing data

In [3]:
# importing numpy
import numpy as np


### Creating arrays with diff dimentions


#### 1D-Arrays

In [4]:
# 1D-Array
a=np.array([2,3,5,47,8])
a

array([ 2,  3,  5, 47,  8])

In [7]:
a.dtype # ddata type of array

dtype('int32')

In [9]:
a=np.array([1,2,3,'s'])
a

array(['1', '2', '3', 's'], dtype='<U11')

In [10]:
# for add a new one element
a=np.append(a,5)
a

array(['1', '2', '3', 's', '5'], dtype='<U11')

In [11]:
#for adding group of elememts 
a=np.append(a,[1,2,5,6,8,'j'])
a

array(['1', '2', '3', 's', '5', '1', '2', '5', '6', '8', 'j'],
      dtype='<U11')

In [12]:
# for creating range
a=np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
a=np.arange(1,10,2)
a

array([1, 3, 5, 7, 9])

In [14]:
a=np.arange(2,10,2)
a

array([2, 4, 6, 8])

In [15]:
## memory space
a.nbytes

16

In [16]:
a.itemsize

4

In [17]:
len(a)

4

In [18]:
#linear space between the numbers
a=np.linspace(1,10,20) 
a

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [19]:
a=np.logspace(1,10,20)
a

array([1.00000000e+01, 2.97635144e+01, 8.85866790e+01, 2.63665090e+02,
       7.84759970e+02, 2.33572147e+03, 6.95192796e+03, 2.06913808e+04,
       6.15848211e+04, 1.83298071e+05, 5.45559478e+05, 1.62377674e+06,
       4.83293024e+06, 1.43844989e+07, 4.28133240e+07, 1.27427499e+08,
       3.79269019e+08, 1.12883789e+09, 3.35981829e+09, 1.00000000e+10])

In [21]:
a=np.full(10,'a')
a

array(['a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a'], dtype='<U1')

In [22]:
np.full(10,25)

array([25, 25, 25, 25, 25, 25, 25, 25, 25, 25])

In [23]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [24]:
a=np.ones(10,dtype=int)

In [25]:
a

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [26]:
a=np.zeros(10)

In [27]:
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [29]:
a.ndim

1

### 2D-Arrays

In [31]:
a=np.full((2,4),15)
a

array([[15, 15, 15, 15],
       [15, 15, 15, 15]])

In [34]:
s=np.array([[2,2,5],[2,5,5],[4,5,4]])
s

array([[2, 2, 5],
       [2, 5, 5],
       [4, 5, 4]])

In [35]:
s.ndim

2

In [36]:
s.nbytes

36

In [37]:
s.itemsize

4

In [38]:
len(s)

3

In [39]:
s.size

9

### 3D -Array

In [41]:
a=np.array([[[1,2,5,3],[4,5,6,8]],[[4,5,6,9],[4,5,4,7]]])
a

array([[[1, 2, 5, 3],
        [4, 5, 6, 8]],

       [[4, 5, 6, 9],
        [4, 5, 4, 7]]])

In [42]:
a.ndim

3

In [43]:
len(a)

2

In [44]:
a.size

16

### Multi Dimentional Array

In [53]:
e=np.array([[1,2,5,6],[2,5,6,9]],ndmin=3)
e

array([[[1, 2, 5, 6],
        [2, 5, 6, 9]]])

In [6]:
import numpy as np
e=np.array([[1,2,3],[1,2,5]],ndmin=2)
e

array([[1, 2, 3],
       [1, 2, 5]])

In [50]:
e.ndim

25

### Accessing of elemets from an array

#### 1D-Array Acessing

In [54]:
a=np.array([1,2,3,6,5,4])
a

array([1, 2, 3, 6, 5, 4])

In [55]:
a[-1]

4

In [56]:
a[3]

6

In [58]:
a[2:]

array([3, 6, 5, 4])

In [59]:
a[:2]

array([1, 2])

### 2D-Acessing

In [60]:
b=np.array([[1,2,3,4],[2,3,4,5],[3,5,6,7]])
b

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 5, 6, 7]])

In [61]:
b[2]

array([3, 5, 6, 7])

In [62]:
b[0,2]

3

In [63]:
b[2,-1]

7

In [64]:
b[2,3]

7

In [65]:
b[1:,-1]

array([5, 7])

In [66]:
b[2:2]

array([], shape=(0, 4), dtype=int32)

### 3D Accessing

In [68]:
e

array([[[1, 2, 5, 6],
        [2, 5, 6, 9]]])

In [72]:
e=np.array([[[1,2,5,6],[1,2,5,3]],[[4,5,6,1],[1,2,5,6]]])
e

array([[[1, 2, 5, 6],
        [1, 2, 5, 3]],

       [[4, 5, 6, 1],
        [1, 2, 5, 6]]])

In [73]:
e.ndim

3

In [74]:
e[0]

array([[1, 2, 5, 6],
       [1, 2, 5, 3]])

In [75]:
e[0,0]

array([1, 2, 5, 6])

In [76]:
e[1,0]

array([4, 5, 6, 1])

In [77]:
e[1,1]

array([1, 2, 5, 6])

In [78]:
e[1:,-1]

array([[1, 2, 5, 6]])

In [79]:
e[1:,-2]

array([[4, 5, 6, 1]])

In [80]:
e

array([[[1, 2, 5, 6],
        [1, 2, 5, 3]],

       [[4, 5, 6, 1],
        [1, 2, 5, 6]]])

### Shape of the Arrays

In [81]:
a

array([1, 2, 3, 6, 5, 4])

In [82]:
a.shape

(6,)

In [83]:
e.shape

(2, 2, 4)

In [86]:
e

array([[[1, 2, 5, 6],
        [1, 2, 5, 3]],

       [[4, 5, 6, 1],
        [1, 2, 5, 6]]])

In [84]:
b.shape

(3, 4)

In [85]:
b

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 5, 6, 7]])

### Reshape of An Array
##### Chnageing the shape of the array and giving the new structure

In [87]:
b

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 5, 6, 7]])

In [94]:
b.reshape(2,6)

array([[1, 2, 3, 4, 2, 3],
       [4, 5, 3, 5, 6, 7]])

In [97]:
a=np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [103]:
a.reshape(3,3)


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [243]:
a=np.arange(1,13)

In [108]:
a.itemsize

4

In [106]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

### 1D-3D

In [244]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [125]:
a=a.reshape(3,4,1)

In [123]:
e

array([[[1, 2, 5, 6],
        [1, 2, 5, 3]],

       [[4, 5, 6, 1],
        [1, 2, 5, 6]]])

In [256]:
a.reshape(1,6,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [132]:
a.reshape(3,-1)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [133]:
a.reshape(-1,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [249]:
a.reshape(2,2,3,1)

array([[[[ 1],
         [ 2],
         [ 3]],

        [[ 4],
         [ 5],
         [ 6]]],


       [[[ 7],
         [ 8],
         [ 9]],

        [[10],
         [11],
         [12]]]])

### Iteration of Arrays

### 1D-Array

In [150]:
a=np.array([1,2,3,6,5,4,2,3,6])

In [151]:
for i in a:
    print(i,end=' ')

1 2 3 6 5 4 2 3 6 

In [153]:
### 2D-Array
b=a.reshape(3,3)

In [154]:
b

array([[1, 2, 3],
       [6, 5, 4],
       [2, 3, 6]])

In [155]:
for i in b:
    for j in i:
        print(j,end=' ')

1 2 3 6 5 4 2 3 6 

In [156]:
b

array([[1, 2, 3],
       [6, 5, 4],
       [2, 3, 6]])

In [161]:
q=b.reshape(3,1,3)

In [158]:
### method for iterating in array elememt in numpy
#### nditer
b

array([[1, 2, 3],
       [6, 5, 4],
       [2, 3, 6]])

In [160]:
for i in np.nditer(b):
    print(i,end=' ')

1 2 3 6 5 4 2 3 6 

In [163]:
for i in np.nditer(q):
    print(i,end=' ')

1 2 3 6 5 4 2 3 6 

### Joining of Arrays

In [164]:
a=np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [174]:
b=np.arange(11,23).reshape(4,3)
b

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19],
       [20, 21, 22]])

In [175]:
c=np.concatenate((a,b))
c

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19],
       [20, 21, 22]])

### Stastical and Mathematical Operations on Arrays

In [176]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [177]:
np.min(a)

1

In [178]:
np.max(a)

9

In [179]:
np.mean(a)

5.0

In [180]:
np.argmax(a)

8

In [181]:
np.argmin(a)

0

In [182]:
np.average(a)

5.0

In [183]:
np.median(a)

5.0

In [184]:
np.var(a)

6.666666666666667

In [185]:
np.std(a)

2.581988897471611

In [186]:
np.sum(a)

45

In [187]:
np.min(a,1) #------> 1 refters to row 
            #------->0 refters to colume

array([1, 4, 7])

In [188]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [189]:
np.min(a,0)

array([1, 2, 3])

In [190]:
np.argmax(a,0)

array([2, 2, 2], dtype=int64)

In [191]:
np.std(a,1)

array([0.81649658, 0.81649658, 0.81649658])

In [192]:
np.var(a,0)

array([6., 6., 6.])

### Stacking
* Organizing/arrangeing in an order:
    - vertical
    - horizontal

In [193]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [194]:
np.hstack(a)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [195]:
np.vstack(a)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [197]:
b=np.arange(11,20).reshape(3,3)
b

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [199]:
np.vstack((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [201]:
np.hstack((a,b))

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16],
       [ 7,  8,  9, 17, 18, 19]])

In [202]:
np.exp(a)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [203]:
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [204]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [205]:
np.tan(a)

array([[ 1.55740772, -2.18503986, -0.14254654],
       [ 1.15782128, -3.38051501, -0.29100619],
       [ 0.87144798, -6.79971146, -0.45231566]])

In [206]:
np.cos(a)

array([[ 0.54030231, -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029],
       [ 0.75390225, -0.14550003, -0.91113026]])

In [207]:
np.log(a)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [208]:
np.log2(a)

array([[0.        , 1.        , 1.5849625 ],
       [2.        , 2.32192809, 2.5849625 ],
       [2.80735492, 3.        , 3.169925  ]])

In [209]:
np.log10(a)

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125],
       [0.84509804, 0.90308999, 0.95424251]])

In [211]:
np.remainder(a,4)

array([[1, 2, 3],
       [0, 1, 2],
       [3, 0, 1]], dtype=int32)

In [212]:
np.degrees(a)

array([[ 57.29577951, 114.59155903, 171.88733854],
       [229.18311805, 286.47889757, 343.77467708],
       [401.07045659, 458.3662361 , 515.66201562]])

In [213]:
np.diff(a)

array([[1, 1],
       [1, 1],
       [1, 1]])

In [215]:
np.ediff1d(a)

array([1, 1, 1, 1, 1, 1, 1, 1])

In [218]:
np.i0(a)  #besel values

array([[   1,    2,    4],
       [  11,   27,   67],
       [ 168,  427, 1093]])

In [219]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [220]:
np.mod(a,4)

array([[1, 2, 3],
       [0, 1, 2],
       [3, 0, 1]], dtype=int32)

In [221]:
np.power(a,4)

array([[   1,   16,   81],
       [ 256,  625, 1296],
       [2401, 4096, 6561]], dtype=int32)

In [222]:
np.reciprocal(a)

array([[1, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [223]:
np.multiply(a,5)

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [224]:
np.divide(a,4)

array([[0.25, 0.5 , 0.75],
       [1.  , 1.25, 1.5 ],
       [1.75, 2.  , 2.25]])

In [226]:
c=np.array([1+2j,2+3j])

In [227]:
np.real(c)

array([1., 2.])

In [228]:
np.imag(c)

array([2., 3.])

#### Ravel and Flatten

In [229]:
o=np.array([1,2,3,4,5])
o

array([1, 2, 3, 4, 5])

In [230]:
copy=o.ravel()

In [231]:
copy

array([1, 2, 3, 4, 5])

In [232]:
o

array([1, 2, 3, 4, 5])

In [234]:
copy[0]=100

In [235]:
copy

array([100,   2,   3,   4,   5])

In [236]:
o

array([100,   2,   3,   4,   5])

In [237]:
copyf=o.flatten()
copyf

array([100,   2,   3,   4,   5])

In [238]:
copyf[0]=1

In [239]:
copyf

array([1, 2, 3, 4, 5])

In [240]:
o

array([100,   2,   3,   4,   5])